version: '3'

services:

  backend:
    image: esurijon/listadigital-backend
    networks:
      - listadigital

  front:
    image: esurijon/listadigital-frontend
    ports:
      - "80:80"
    networks:
      - listadigital

networks:
  listadigital:
